name: Python application

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

on: [pull_request]

jobs:
  build:
    name: "example/dummy/test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const ref = context.payload.pull_request.head.ref;
            console.log(ref);
            if (ref.startsWith("mq-")) {
              core.setFailed("Branch name starts with 'mq-'");
            }
